# Change these first
owner: Limbo-Studios # Your GitHub organization or username, where this repository lives
repo: limbo-status-page # The name of this repository

sites:
  - name: Limbo Yggdrasil Multiplayer Session Service
    url: https://minecraft.everland.lsmp.tech
    expectedStatusCodes:
      - 200
  - name: Limbo Yggdrasil Authserver
    url: https://minecraft.everland.lsmp.tech
    expectedStatusCodes:
      - 200
  - name: Mojang Multiplayer Session Service
    url: http://session.minecraft.net
    expectedStatusCodes:
      - 404
  - name: Skins
    url: https://minecraft.everland.lsmp.tech
    expectedStatusCodes:
      - 200
  - name: Limbo Yggdrasil Public API
    url: https://minecraft.everland.lsmp.tech/authlib-injector
  - name: Main LimboAuth Website
    url: https://auth.everland.lsmp.tech/
    expectedStatusCodes:
      - 200
      - 200
  - name: Limbo Yggdrasil
    url: https://minecraft.everland.lsmp.tech
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lsmp.tech
  #baseUrl: /limbo-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Página de estado de los servicios de Limbo
  introTitle: "Everland Launcher utiliza esta página para obtener el estado de la API de Yggdrasil en LimboAuth."
  introMessage: No somos Mojang o Microsoft
  navbar:
    - title: Inicio
      href: /


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
